version: "3"

services:
    fc-docker-c2-mysql:
        build: ./mysql
        volumes:
            - ./mysql/db:/var/lib/mysql

    fc-docker-c2-node:
        build: ./node
        volumes:
            - ./node:/usr/src/app
        depends_on:
            - fc-docker-c2-mysql

    fc-docker-c2-nginx:
        build: ./nginx
        ports:
            - 8080:80
        depends_on:
            - fc-docker-c2-node
